# Generated by Django 4.2 on 2025-12-24 16:01

from django.db import migrations


def remove_deprecated_questions(apps, schema_editor):
    Question = apps.get_model('questions', 'Question')
    # Delete questions with types that are being removed
    Question.objects.filter(question_type__in=['short_answer', 'code']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.RunPython(remove_deprecated_questions),
    ]
