# Generated by Django 4.2 on 2025-12-15 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='proctoring/snapshots/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trust_score', models.FloatField(default=1.0, help_text='AI calculated trust score (0.0-1.0)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='examinations.examsession')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
