# Generated by Django 4.2 on 2025-12-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_proctoringsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
