# Generated by Django 4.2 on 2025-12-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0003_examsession_grading_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examsession',
            name='examination_exam_id_fef13f_idx',
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'student'], name='examination_exam_id_f45d5c_idx'),
        ),
    ]
