# Generated by Django 4.2 on 2025-12-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_remove_examsession_examination_exam_id_fef13f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examanswer',
            name='short_answer_text',
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='face_data',
            field=models.JSONField(blank=True, help_text='Face bounding box and landmarks', null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='issue_type',
            field=models.CharField(blank=True, help_text='Reason for low score', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='grading_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('graded', 'Reviewed')], default='pending', max_length=20),
        ),
    ]
